### ISSUE TITLE
ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.

### ISSUE THREAD

**Issue by jolespin** [Vini2/GraphBin#13] opened 2021-03-27 20:30 UTC
```python
(graphbin_env) jespinozlt2-osx:GraphBin jespinoz$ python graphbin --graph ~/assembly_graph_with_scaffolds.gfa --binned ~/scaffolds_to_bins.csv --output graphin_output --paths ~/scaffolds.paths --assembler "spades"
2021-03-27 13:24:53,962 - INFO - Welcome to GraphBin: Refined Binning of Metagenomic Contigs using Assembly Graphs.
2021-03-27 13:24:53,962 - INFO - This version of GraphBin makes use of the assembly graph produced by SPAdes which is based on the de Bruijn graph approach.
2021-03-27 13:24:53,962 - INFO - Input arguments:
2021-03-27 13:24:53,962 - INFO - Assembly graph file: /Users/jespinoz/assembly_graph_with_scaffolds.gfa
2021-03-27 13:24:53,962 - INFO - Contig paths file: /Users/jespinoz/scaffolds.paths
2021-03-27 13:24:53,962 - INFO - Existing binning output file: /Users/jespinoz/binning/scaffolds_to_bins.csv
2021-03-27 13:24:53,962 - INFO - Final binning output file: graphin_output/
2021-03-27 13:24:53,962 - INFO - Maximum number of iterations: 100
2021-03-27 13:24:53,962 - INFO - Difference threshold: 0.1
2021-03-27 13:24:53,962 - INFO - GraphBin started
2021-03-27 13:24:53,964 - INFO - Number of bins available in the initial binning result: 2
2021-03-27 13:24:53,964 - INFO - Constructing the assembly graph
2021-03-27 13:24:54,173 - INFO - Total number of contigs available: 25728
2021-03-27 13:24:59,473 - INFO - Total number of edges in the assembly graph: 1373
2021-03-27 13:24:59,473 - INFO - Obtaining the initial binning result
2021-03-27 13:24:59,473 - ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.
2021-03-27 13:24:59,473 - INFO - Exiting GraphBin... Bye...!
```

I can't figure out what is going wrong with my files.  I used metaspades and MaxBin2 for my binning.  

Here is my version: 
```python
(graphbin_env) jespinozlt2-osx:GraphBin jespinoz$ python graphbin --version
GraphBin version 1.3
```

Also, "SPAdes" isn't an accepted argument.

Any help would be greatly appreciated. 

[files.zip](https://github.com/Vini2/GraphBin/files/6216363/files.zip)

**Comment by Vini2** [comment] 2021-03-29 03:05
Dear @jolespin,

Thank you for posting the issue with the relevant data. I went through your files and found that the binning results file `scaffolds_to_bins.csv` is not in the format required as input for GraphBin. As the [documentation](https://github.com/Vini2/GraphBin#input-format) outlines, the binning output file should have comma separated values `(contig_identifier, bin_number)` for each contig.

GraphBin provides a support script named [prepresult.py](https://github.com/Vini2/GraphBin/blob/master/support/prepResult.py) to generate similar files once the initial binning output folder is provided. You can refer to [support/README.md](https://github.com/Vini2/GraphBin/blob/master/support/README.md#prepresultpy) for more details.

Let me know if this won't solve the issue.

Thank you!

**Comment by jolespin** [comment] 2021-03-29 05:21
Thanks for getting back to me.  I just tried it with the bins relabeled and got the same error. 


```
(graphbin_env) jespinozlt2-osx:GraphBin jespinoz$ head /Users/jespinoz/Downloads/files/scaffolds_to_bins.relabeled.csv
NODE_14_length_9160_cov_4.404833,0
NODE_15_length_7837_cov_3.578386,0
NODE_16_length_7509_cov_4.024014,0
NODE_17_length_7205_cov_3.142238,0
NODE_18_length_6867_cov_2.992073,0
NODE_19_length_6076_cov_3.252782,0
NODE_20_length_5936_cov_3.975514,0
NODE_21_length_5583_cov_3.496020,0
NODE_22_length_5539_cov_3.360686,0
NODE_24_length_5345_cov_3.093384,0
```

Most of the binning programs output alphanumeric strings so it seems a bit more difficult to integrate this into existing pipelines.  Does `prepresult.py` format the graph and contigs/scaffolds as well?

**Comment by Vini2** [comment] 2021-03-29 05:46
The `(contig_identifier, bin_number)` pairs should be in the form 
```
NODE_1,1
NODE_2,1
NODE_3,1
NODE_4,2
NODE_5,2
...
```
Note that the numbering of bins should start from 1

`prepresult.py` handles all these cases and outputs the binning result as shown. You can first run the `prepresult.py` script as
```
python prepResult.py --binned /path/to/folder_with_binning_result --assembler spades --output /path/to/output_folder
```
Since MaxBin2 outputs the binning result to .fasta files for each bin, you can provide the path containing these .fasta files to the `--binned` option.

After getting the formatted binning result, you can input it to GraphBin.

Let me know if it still doesn't work.

**Comment by jolespin** [comment] 2021-03-29 17:55
I'll give it a try.  So it truncates all of the contig identifiers?  Thanks for including the `prepResult.py` to preprocess everything. 

In the future would it be possible to make this a bit more seamless to integrate into existing pipelines? For example, I'm running [metabat2](https://bitbucket.org/berkeleylab/metabat) and [maxbin2](https://sourceforge.net/projects/maxbin2/) then I feed everything into [DAS_Tool](https://github.com/cmks/DAS_Tool) which takes in `[scaffold]\t[bin]` tsv files with the identifiers unmodified (created using https://github.com/cmks/DAS_Tool/blob/master/src/Scaffolds2Bin_to_Fasta.sh).  

If graphbin could take in unmodified identifiers and do the conversion in the backend automatically it would make it much more practical to use in a complicated pipeline where similar versions to the required files are already generated.   In an ideal scenario, it would be awesome to have DAS_Tool take in the pre/post graphbin binning for it to calculate a consensus for everything w/ as few steps as possible.

**Comment by Vini2** [comment] 2021-03-29 22:23
That would be a great option. I will modify GraphBin to support a more generic convention for inputs and outputs as the one you mentioned `[scaffold]\t[bin]` where scaffolds/contigs and the bins will have their original identifiers and add a new version of GraphBin.

Thank you very much for the suggestion! I will keep this issue open so you can let me know if it still doesn't work.

**Comment by JSSaini** [comment] 2021-04-14 14:33
Hello, I have a similar issue.  I can see that it is reporting my binning file (file attached) to contain **two bins** . However, I can confirm that my binning file has just one bin number. Please see the file attached. 

[clustering_gt1000_mod.zip](https://github.com/Vini2/GraphBin/files/6311511/clustering_gt1000_mod.zip)

 to contain two bins instead of one.                                                                                                                                                    ```graphbin --assembler spades --graph /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15p5_Map_GBII/assembly_graph_after_simplification.gfa --paths /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15p5_Map_GBII/contigs.paths --binned /home/users/s/saini7/scratch/MS2/Anvio2/mapping2/spa_concoct/clustering_gt1000_mod.csv --output ./```

```2021-04-14 16:25:44,109 - INFO - Welcome to GraphBin: Refined Binning of Metagenomic Contigs using Assembly Graphs.
2021-04-14 16:25:44,120 - INFO - This version of GraphBin makes use of the assembly graph produced by SPAdes which is based on the de Bruijn graph approach.
2021-04-14 16:25:44,121 - INFO - Input arguments:
2021-04-14 16:25:44,122 - INFO - Assembly graph file: /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15p5_Map_GBII/assembly_graph_after_simplification.gfa
2021-04-14 16:25:44,123 - INFO - Contig paths file: /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15p5_Map_GBII/contigs.paths
2021-04-14 16:25:44,124 - INFO - Existing binning output file: /home/users/s/saini7/scratch/MS2/Anvio2/mapping2/spa_concoct/clustering_gt1000_mod.csv
2021-04-14 16:25:44,125 - INFO - Final binning output file: ./
2021-04-14 16:25:44,126 - INFO - Maximum number of iterations: 100
2021-04-14 16:25:44,127 - INFO - Difference threshold: 0.1
2021-04-14 16:25:44,128 - INFO - GraphBin started
2021-04-14 16:25:44,193 - INFO - Number of bins available in the initial binning result: 2
2021-04-14 16:25:44,194 - INFO - Constructing the assembly graph
2021-04-14 16:25:44,357 - INFO - Total number of contigs available: 2655
2021-04-14 16:25:47,111 - INFO - Total number of edges in the assembly graph: 10554
2021-04-14 16:25:47,112 - INFO - Obtaining the initial binning result
2021-04-14 16:25:47,116 - ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.
2021-04-14 16:25:47,117 - INFO - Exiting GraphBin... Bye...!```

**Comment by Vini2** [comment] 2021-04-16 00:25
Hello @JSSaini,

Your binning file has a header `contig_id,cluster_id` which should not be included. This is why GraphBin counts `cluster_id` and `43` as 2 bins. Also I noticed that your contig ids are in the form `c_00000000000*`. These contig ids should be the form `NODE_*` as found ids found in your `contigs.paths` file. You can double check that as well.

GraphBin provides a support script named [prepresult.py](https://github.com/Vini2/GraphBin/blob/master/support/prepResult.py) to generate the binning file once the initial binning output folder is provided. You can refer to [support/README.md](https://github.com/Vini2/GraphBin/blob/master/support/README.md#prepresultpy) for more details.

Let me know if this won't solve the issue.

Thank you!

**Comment by JSSaini** [comment] 2021-04-16 11:30
Still the same error, this time I made sure I have given the appropriate binning file. Have you tried this tool with concoct binning results? Thank you. 
[conc_graph.txt](https://github.com/Vini2/GraphBin/files/6324582/conc_graph.txt)


```[saini7@login2 spa_concoct2]$ graphbin --assembler spades --graph /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15mw_Map_GBII/assembly_graph_with_scaffolds.gfa --paths /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15mw_Map_GBII/contigs.paths --binned /home/users/s/saini7/scratch/MS2/Anvio2/conc2/spa_concoct2/conc_graph.csv --output ./genomes
2021-04-16 13:27:36,494 - INFO - Welcome to GraphBin: Refined Binning of Metagenomic Contigs using Assembly Graphs.
2021-04-16 13:27:36,591 - INFO - This version of GraphBin makes use of the assembly graph produced by SPAdes which is based on the de Bruijn graph approach.
2021-04-16 13:27:36,593 - INFO - Input arguments:
2021-04-16 13:27:36,595 - INFO - Assembly graph file: /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15mw_Map_GBII/assembly_graph_with_scaffolds.gfa
2021-04-16 13:27:36,596 - INFO - Contig paths file: /home/users/s/saini7/scratch/MS2/Anvio2/Spades_13_15mw_Map_GBII/contigs.paths
2021-04-16 13:27:36,597 - INFO - Existing binning output file: /home/users/s/saini7/scratch/MS2/Anvio2/conc2/spa_concoct2/conc_graph.csv
2021-04-16 13:27:36,599 - INFO - Final binning output file: ./genomes/
2021-04-16 13:27:36,600 - INFO - Maximum number of iterations: 100
2021-04-16 13:27:36,602 - INFO - Difference threshold: 0.1
2021-04-16 13:27:36,603 - INFO - GraphBin started
2021-04-16 13:27:36,609 - INFO - Number of bins available in the initial binning result: 1
2021-04-16 13:27:36,610 - INFO - Constructing the assembly graph
2021-04-16 13:27:36,852 - INFO - Total number of contigs available: 2845
2021-04-16 13:27:37,584 - INFO - Total number of edges in the assembly graph: 11581
2021-04-16 13:27:37,585 - INFO - Obtaining the initial binning result
2021-04-16 13:27:37,589 - ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.
2021-04-16 13:27:37,590 - INFO - Exiting GraphBin... Bye...!```

**Comment by Vini2** [comment] 2021-04-18 05:01
Hi @JSSaini,

I fixed some errors in the indexing of the input bins. Can you please get the latest git pull of GraphBin and check your results? It should work fine now. 

Let me know if this won't solve the issue.

Thank you!

PS: I haven't added a new release yet with the fix as I plan to add some more fixes. I will add a new release including all the fixes ASAP.

**Comment by Vini2** [comment] 2021-04-20 05:09
Hello @jolespin and @JSSaini,

I have added a new release of GraphBin with fixes to this issue. Please give it a try when you have time. 

https://github.com/Vini2/GraphBin/releases/tag/v1.4

Thank you very much for the input.

**Comment by jolespin** [comment] 2021-04-20 08:47
"Fixed naming of SPAdes contigs to have original contig identifiers and updated prepResult.py to reflect this fix." 🙏🏽 thank you! This will make it much easier to implement into existing pipelines

**Comment by Vini2** [comment] 2021-04-26 05:24
Closing issue after fixing.

**Closed by Vini2** 2021-04-26 05:24 UTC
Labels: enhancement, help wanted
